# TRMNLP configuration
---
# auto-reload when files change
watch:
  - src
  - .trmnlp.yml

# override variables for development
variables:
  trmnl:
    user:
      utc_offset: 3600  # mock UTC+1; change to match your local offset for timezone testing
